apiVersion: v1
kind: ConfigMap
metadata:
  name: mestory-config
  namespace: mestory
data:
  NODE_ENV: "production"
  PORT_API: "4000"
  PORT_WEB: "3000"
  NEXT_PUBLIC_API_URL: "https://mestory.ru/api"
  CORS_ORIGIN: "*"
---
apiVersion: v1
kind: Secret
metadata:
  name: mestory-secrets
  namespace: mestory
type: Opaque
stringData:
  POSTGRES_DB: "mestory"
  POSTGRES_USER: "mestory"
  POSTGRES_PASSWORD: "mestory_k8s_secure_pass_2026"
  DATABASE_URL: "postgresql://mestory:mestory_k8s_secure_pass_2026@mestory-postgres.mestory.svc.cluster.local:5432/mestory?schema=public"
  JWT_SECRET: "mestory-k8s-jwt-super-secret-key-rostov-2026"
