apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mestory

resources:
  - 00-namespace.yaml
  - 01-secrets-config.yaml
  - 02-postgres.yaml
  - 03-api.yaml
  - 04-web.yaml
  - 05-ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: mestory
  app.kubernetes.io/managed-by: kustomize
